"use client";

import React, { createContext, useContext, useState, ReactNode } from "react";

// Translations copied from Home (Hero) page
export const translations: Record<string, any> = {
  en: {
    navHome: "Home",
    navAbout: "About",
    navServices: "Services",
    navAstrology: "Astrology",
    navTestimonials: "Testimonials",
    navBlog: "Blog",
    navContact: "Contact",
    heroHeadline: "Authentic Vedic Pujas, Just a Click Away",
    heroSubText1:
      "Experience the divine grace of Sanatan Dharma through authentic Vedic Pujas, personalized Astrology, and sacred rituals performed by trusted Pandits with 12+ years of experience across India.",
    heroSubText2:
      "Bringing peace, prosperity, and positive energy to every home with devotion and purity.",
    bookPoojaNow: "📿 Book Your Pooja Now",
    bookAstrology: "🔮 Book Astrology Session",
    servicesTitle: "Our Divine Services",
    poojaServices: "Pooja Services",
    astrologyServices: "Astrology",
    onlinePooja: "Online / E-Pooja",
    learnMore: "Learn More →",
    aboutTitle: "Meet Pandit Aditya Narayan Ji",
    aboutText:
      "With over 12 years of experience performing sacred rituals across India, Pandit Aditya Narayan Ji is known for authentic vedic poojas done as per Sanatan Vidhi. Guided by his father, a revered priest, he continues a legacy of devotion and spiritual service.",
    readMore: "Read More",
    whyChooseUsTitle: "Why Choose Us?",
    spiritualGuides: "Spiritual Guides",
    guidesDesc: "Priests, Pandits, Religious Experts & Consultants",
    typesOfPooja: "Types of Pooja",
    poojaDesc: "Covering all major Vedic rituals and ceremonies",
    poojasPerformed: "Poojas Performed",
    performedDesc: "Bringing peace and blessings across all India",
    popularPoojasTitle: "Most Popular Poojas",
    bookNow: "Book Now",
    testimonialsTitle: "Words of Devotion",
    bookingTitle: "Book a Divine Experience",
    fullName: "Full Name",
    phone: "Phone Number",
    poojaType: "Pooja Type",
    preferredDate: "Preferred Date",
    message: "Additional Message",
    sendOnWhatsApp: "Send Booking Request on WhatsApp",
    footerContact: "Vedic Pooja & Astrology Services",
    footerSpecialPoojas: "Special Pooja Services",
    footerPoojaServices: "Pooja Services",
    footerQuickLinks: "Quick Links",
    footerContactInfo: "Contact Info",
    // Astrology page translations
    astrologyHeroTitle:
      "Discover the Power of Astrology — With Expert Guidance",
    all: "All",
    marriage: "Marriage",
    career: "Career",
    health: "Health",
    finance: "Finance",
    spiritual: "Spiritual",
    footerCTA: "Schedule your astrology consultation on WhatsApp right now 📱.",
    consultationPrice: "Consultation starts at",
    bookYourSession: "Book your session!",
    consultNow: "Consult Now",
  },
  hi: {
    navHome: "होम",
    navAbout: "हमारे बारे में",
    navServices: "सेवाएं",
    navAstrology: "ज्योतिष",
    navTestimonials: "प्रशंसापत्र",
    navBlog: "ब्लॉग",
    navContact: "संपर्क",
    heroHeadline: "✨ अब घर बैठे करवाएं असली वैदिक पूजा",
    heroSubText1:
      "सनातन धर्म की दिव्य कृपा का अनुभव करें — अनुभवी और विश्वसनीय पंडितों द्वारा की जाने वाली शुद्ध वैदिक पूजाएं, ज्योतिष परामर्श और विशेष अनुष्ठान के माध्यम से।",
    heroSubText2:
      "📿 श्रद्धा, शुद्धता और वेदिक विधि से आपके घर में सुख, समृद्धि और सकारात्मक ऊर्जा लाने का हमारा संकल्प।",
    bookPoojaNow: "🕉️ अभी अपनी पूजा बुक करें",
    bookAstrology: "🔮 ज्योतिष सत्र बुक करें",
    servicesTitle: "हमारी दिव्य सेवाएं",
    poojaServices: "पूजा सेवाएं",
    astrologyServices: "ज्योतिष",
    onlinePooja: "ऑनलाइन / ई-पूजा",
    learnMore: " और जानें →",
    aboutTitle: "मिलिए पंडित आदित्य नारायण जी से",
    aboutText:
      "भारत भर में पवित्र अनुष्ठान करने के 12 से अधिक वर्षों के अनुभव के साथ, पंडित आदित्य नारायण जी सनातन विधि के अनुसार किए गए प्रामाणिक वैदिक पूजा के लिए जाने जाते हैं। अपने पिता, एक सम्मानित पुजारी के मार्गदर्शन में, वह भक्ति और आध्यात्मिक सेवा की विरासत को जारी रखे हुए हैं।",
    readMore: "और पढ़ें",
    whyChooseUsTitle: "हमें क्यों चुनें?",
    spiritualGuides: "आध्यात्मिक मार्गदर्शक",
    guidesDesc: "पुजारी, पंडित, धार्मिक विशेषज्ञ और सलाहकार",
    typesOfPooja: "पूजा के प्रकार",
    poojaDesc: "सभी प्रमुख वैदिक अनुष्ठानों और समारोहों को शामिल करते हुए",
    poojasPerformed: "पूजा संपन्न हुई",
    performedDesc: "पूरे भारत में शांति और आशीर्वाद लाना",
    popularPoojasTitle: "सबसे लोकप्रिय पूजा",
    bookNow: "अभी बुक करें",
    testimonialsTitle: "भक्ति के शब्द",
    bookingTitle: "एक दिव्य अनुभव बुक करें",
    fullName: "पूरा नाम",
    phone: "फ़ोन नंबर",
    poojaType: "पूजा का प्रकार",
    preferredDate: "पसंदीदा तारीख",
    message: "अतिरिक्त संदेश",
    sendOnWhatsApp: "व्हाट्सएप पर बुकिंग अनुरोध भेजें",
    footerContact: "वैदिक पूजा और ज्योतिष सेवाएं",
    footerSpecialPoojas: "विशेष पूजा सेवाएं",
    footerPoojaServices: "पूजा सेवाएं",
    footerQuickLinks: "त्वरित लिंक",
    footerContactInfo: "संपर्क जानकारी",
    // Astrology page translations
    astrologyHeroTitle:
      "ज्योतिष की शक्ति की खोज करें — विशेषज्ञ मार्गदर्शन के साथ",
    all: "सभी",
    marriage: "विवाह",
    career: "करियर",
    health: "स्वास्थ्य",
    finance: "वित्तीय",
    spiritual: "आध्यात्मिक",
    footerCTA: "अभी व्हाट्सएप पर अपनी ज्योतिष सलाह शेड्यूल करें 📱।",
    consultationPrice: "सलाह शुरू होती है",
    bookYourSession: "अपना सत्र बुक करें!",
    consultNow: "अभी सलाह लें",
  },
  mr: {
    navHome: "मुख्यपृष्ठ",
    navAbout: "आमच्याबद्दल",
    navServices: "सेवा",
    navAstrology: "ज्योतिष",
    navTestimonials: "प्रशंसापत्र",
    navBlog: "ब्लॉग",
    navContact: "संपर्क",
    heroHeadline: "✨ घरबसल्या अनुभवा खऱ्या वैदिक पूजांचा दिव्य अनुभव",
    heroSubText1:
      "सनातन धर्माच्या आशीर्वादाने अनुभवा खऱ्या वैदिक पूजा, वैयक्तिक ज्योतिष उपाय आणि पवित्र विधी, आमचे १२+ वर्षांचा अनुभव असलेले विश्वसनीय पुजारी पुणे, मुंबई, नाशिक, नागपूर आणि इतर शहरांमध्ये सेवा देतात।",
    heroSubText2:
      "📿 आपल्या घरी शांती, समृद्धी आणि सकारात्मक ऊर्जा आणण्यासाठी आम्ही समर्पित आहोत।",
    bookPoojaNow: "🕉️ आत्ताच आपली पूजा बुक करा",
    bookAstrology: "🔮 ज्योतिष सत्र बुक करा",
    servicesTitle: "आमच्या दिव्य सेवा",
    poojaServices: "पूजा सेवा",
    astrologyServices: "ज्योतिष",
    onlinePooja: "ऑनलाइन / ई-पूजा",
    learnMore: "अधिक जाणून घ्या →",
    aboutTitle: "भेटा पंडित आदित्य नारायण जी",
    aboutText:
      "भारतभर पवित्र विधी करण्याचा 12 वर्षांपेक्षा जास्त अनुभव असलेले पंडित आदित्य नारायण जी सनातन विधीनुसार केलेल्या अस्सल वैदिक पूजेसाठी ओळखले जातात। त्यांचे वडील, एक आदरणीय पुजारी, यांच्या मार्गदर्शनाखाली ते भक्ती आणि आध्यात्मिक सेवेचा वारसा पुढे चालवत आहेत।",
    readMore: "अधिक वाचा",
    whyChooseUsTitle: "आम्हाला का निवडा?",
    spiritualGuides: "आध्यात्मिक मार्गदर्शक",
    guidesDesc: "पुजारी, पंडित, धार्मिक तज्ञ आणि सल्लागार",
    typesOfPooja: "पूजेचे प्रकार",
    poojaDesc: "सर्व प्रमुख वैदिक विधी आणि समारंभ समाविष्ट आहेत",
    poojasPerformed: "पूजा केली",
    performedDesc: "संपूर्ण भारतात शांती आणि आशीर्वाद आणत आहे",
    popularPoojasTitle: "सर्वात लोकप्रिय पूजा",
    bookNow: "आता बुक करा",
    testimonialsTitle: "भक्तीचे शब्द",
    bookingTitle: "एक दिव्य अनुभव बुक करा",
    fullName: "पूर्ण नाव",
    phone: "फोन नंबर",
    poojaType: "पूजेचा प्रकार",
    preferredDate: "पसंतीची तारीख",
    message: "अतिरिक्त संदेश",
    sendOnWhatsApp: "व्हॉट्सॲपवर बुकिंग विनंती पाठवा",
    footerContact: "वैदिक पूजा आणि ज्योतिष सेवा",
    footerSpecialPoojas: "विशेष पूजा सेवा",
    footerPoojaServices: "पूजा सेवा",
    footerQuickLinks: "जलद लिंक्स",
    footerContactInfo: "संपर्क माहिती",
    // Astrology page translations
    astrologyHeroTitle: "विशेषज्ञ मार्गदर्शनासह ज्योतिषाची शक्ती शोधा",
    all: "सर्व",
    marriage: "विवाह",
    career: "करियर",
    health: "आरोग्य",
    finance: "आर्थिक",
    spiritual: "आध्यात्मिक",
    footerCTA: "आत्ताच व्हॉट्सॲपवर तुमची ज्योतिष सल्ला शेड्यूल करा 📱।",
    consultationPrice: "सल्ला सुरू होते",
    bookYourSession: "तुमचे सत्र बुक करा!",
    consultNow: "आता सल्ला घ्या",
  },
  kn: {
    navHome: "ಮುಖಪುಟ",
    navAbout: "ನಮ್ಮ ಬಗ್ಗೆ",
    navServices: "ಸೇವೆಗಳು",
    navAstrology: "ಜ್ಯೋತಿಷ್ಯ",
    navTestimonials: "ಪ್ರಶಂಸಾಪತ್ರಗಳು",
    navBlog: "ಬ್ಲಾಗ್",
    navContact: "ಸಂಪರ್ಕಿಸಿ",
    heroHeadline: "✨ ನಿಜವಾದ ವೇದಿಕ ಪೂಜೆಗಳು — ಈಗ ನಿಮ್ಮ ಕ್ಲಿಕ್ಕಿನಲ್ಲಿ",
    heroSubText1:
      "ಸನಾತನ ಧರ್ಮದ ದಿವ್ಯ ಕೃಪೆಯನ್ನು ಅನುಭವಿಸಿ — 12+ ವರ್ಷಗಳ ಅನುಭವ ಹೊಂದಿದ ವಿಶ್ವಾಸಾರ್ಹ ಪಂಡಿತರು ನೆರವೇರಿಸುವ ಆಸಲಿ ವೇದಿಕ ಪೂಜೆಗಳು, ವೈಯಕ್ತಿಕ ಜ್ಯೋತಿಷ್ಯ ಸಲಹೆ ಮತ್ತು ಪವಿತ್ರ ವಿಧಿಗಳು।",
    heroSubText2:
      "📿 ಭಕ್ತಿಯಿಂದ, ಶುದ್ಧತೆಯಿಂದ ನಿಮ್ಮ ಮನೆಗೆ ಶಾಂತಿ, ಐಶ್ವರ್ಯ ಮತ್ತು ಸಕಾರಾತ್ಮಕ ಶಕ್ತಿಯನ್ನು ತರಲು ನಮ್ಮ ಪ್ರಯತ್ನ।",
    bookPoojaNow: "🕉️ ಈಗಲೇ ನಿಮ್ಮ ಪೂಜೆಯನ್ನು ಬುಕ್ ಮಾಡಿ",
    bookAstrology: "🔮 ಜ್ಯೋತಿಷ್ಯ ಅಧಿವೇಶನವನ್ನು ಬುಕ್ ಮಾಡಿ",
    servicesTitle: "ನಮ್ಮ ದೈವಿಕ ಸೇವೆಗಳು",
    poojaServices: "ಪೂಜಾ ಸೇವೆಗಳು",
    astrologyServices: "ಜ್ಯೋತಿಷ್ಯ",
    onlinePooja: "ಆನ್‌ಲೈನ್ / ಇ-ಪೂಜೆ",
    learnMore: "ಇನ್ನಷ್ಟು ತಿಳಿಯಿರಿ →",
    aboutTitle: "ಪಂಡಿತ್ ಆದಿತ್ಯ ನಾರಾಯಣ್ ಜಿ ಅವರನ್ನು ಭೇಟಿ ಮಾಡಿ",
    aboutText:
      "ಭಾರತದಾದ್ಯಂತ 12 ವರ್ಷಗಳಿಗಿಂತ ಹೆಚ್ಚು ಕಾಲ ಪವಿತ್ರ ಆಚರಣೆಗಳನ್ನು ನಡೆಸಿದ ಅನುಭವದೊಂದಿಗೆ, ಪಂಡಿತ್ ಆದಿತ್ಯ ನಾರಾಯಣ್ ಜಿ ಸನಾತನ ವಿಧಿಯ ಪ್ರಕಾರ ನಡೆಸಲಾಗುವ ಅಧಿಕೃತ ವೈದಿಕ ಪೂಜೆಗಳಿಗೆ ಹೆಸರುವಾಸಿಯಾಗಿದ್ದಾರೆ। ಅವರ ತಂದೆ, ಪೂಜ್ಯ ಅರ್ಚಕರ ಮಾರ್ಗದರ್ಶನದಲ್ಲಿ, ಅವರು ಭಕ್ತಿ ಮತ್ತು ಆಧ್ಯಾತ್ಮಿಕ ಸೇವೆಯ ಪರಂಪರೆಯನ್ನು ಮುಂದುವರಿಸಿದ್ದಾರೆ।",
    readMore: "ಮತ್ತಷ್ಟು ಓದಿ",
    whyChooseUsTitle: "ನಮ್ಮನ್ನು ಏಕೆ ಆರಿಸಬೇಕು?",
    spiritualGuides: "ಆಧ್ಯಾತ್ಮಿಕ ಮಾರ್ಗದರ್ಶಕರು",
    guidesDesc: "ಪುರೋಹಿತರು, ಪಂಡಿತರು, ಧಾರ್ಮಿಕ ತಜ್ಞರು ಮತ್ತು ಸಲಹೆಗಾರರು",
    typesOfPooja: "ಪೂಜೆಯ ವಿಧಗಳು",
    poojaDesc: "ಎಲ್ಲಾ ಪ್ರಮುಖ ವೈದಿಕ ಆಚರಣೆಗಳು ಮತ್ತು ಸಮಾರಂಭಗಳನ್ನು ಒಳಗೊಂಡಿದೆ",
    poojasPerformed: "ಪೂಜೆಗಳನ್ನು ನಡೆಸಲಾಯಿತು",
    performedDesc: "ಭಾರತದಾದ್ಯಂತ ಶಾಂತಿ ಮತ್ತು ಆಶೀರ್ವಾದವನ್ನು ತರುವುದು",
    popularPoojasTitle: "ಅತ್ಯಂತ ಜನಪ್ರಿಯ ಪೂಜೆಗಳು",
    bookNow: "ಈಗಲೇ ಬುಕ್ ಮಾಡಿ",
    testimonialsTitle: "ಭಕ್ತಿಯ ಮಾತುಗಳು",
    bookingTitle: "ಒಂದು ದೈವಿಕ ಅನುಭವವನ್ನು ಬುಕ್ ಮಾಡಿ",
    fullName: "ಪೂರ್ಣ ಹೆಸರು",
    phone: "ದೂರವಾಣಿ ಸಂಖ್ಯೆ",
    poojaType: "ಪೂಜೆಯ ಪ್ರಕಾರ",
    preferredDate: "ಆದ್ಯತೆಯ ದಿನಾಂಕ",
    message: "ಹೆಚ್ಚುವರಿ ಸಂದೇಶ",
    sendOnWhatsApp: "WhatsApp ನಲ್ಲಿ ಬುಕಿಂಗ್ ವಿನಂತಿಯನ್ನು ಕಳುಹಿಸಿ",
    footerContact: "ವೈದಿಕ ಪೂಜೆ ಮತ್ತು ಜ್ಯೋತಿಷ್ಯ ಸೇವೆಗಳು",
    footerSpecialPoojas: "ವಿಶೇಷ ಪೂಜಾ ಸೇವೆಗಳು",
    footerPoojaServices: "ಪೂಜಾ ಸೇವೆಗಳು",
    footerQuickLinks: "ತ್ವರಿತ ಲಿಂಕ್‌ಗಳು",
    footerContactInfo: "ಸಂಪರ್ಕ ಮಾಹಿತಿ",
    // Astrology page translations
    astrologyHeroTitle:
      "ವಿಶೇಷಜ್ಞ ಮಾರ್ಗದರ್ಶನದೊಂದಿಗೆ ಜ್ಯೋತಿಷ್ಯದ ಶಕ್ತಿಯನ್ನು ಕಂಡುಹಿಡಿಯಿರಿ",
    all: "ಎಲ್ಲಾ",
    marriage: "ವಿವಾಹ",
    career: "ವೃತ್ತಿ",
    health: "ಆರೋಗ್ಯ",
    finance: "ಹಣಕಾಸು",
    spiritual: "ಆಧ್ಯಾತ್ಮಿಕ",
    footerCTA:
      "ಈಗಲೇ ವ್ಹಾಟ್ಸ್‌ಆಪ್‌ನಲ್ಲಿ ನಿಮ್ಮ ಜ್ಯೋತಿಷ್ಯ ಸಲಹೆಯನ್ನು ಶೆಡ್ಯೂಲ್ ಮಾಡಿ 📱।",
    consultationPrice: "ಸಲಹೆ ಪ್ರಾರಂಭವಾಗುತ್ತದೆ",
    bookYourSession: "ನಿಮ್ಮ ಅಧಿವೇಶನವನ್ನು ಬುಕ್ ಮಾಡಿ!",
    consultNow: "ಈಗಲೇ ಸಲಹೆ ಪಡೆಯಿರಿ",
  },
  gj: {
    navHome: "હોમ",
    navAbout: "અમારા વિશે",
    navServices: "સેવાઓ",
    navAstrology: "જ્યોતિષ",
    navTestimonials: "પ્રશંસાપત્રો",
    navBlog: "બ્લોગ",
    navContact: "સંપર્ક",
    heroHeadline: "✨ સાચી વૈદિક પૂજા — હવે માત્ર એક ક્લિકમાં",
    heroSubText1:
      "અનુભવો સનાતન ધર્મની દિવ્ય કૃપા દ્વારા ખરી વૈદિક પૂજા, વ્યક્તિગત જ્યોતિષ સલાહ અને પવિત્ર વિધિઓ, જે 12+ વર્ષના અનુભવ ધરાવતા વિશ્વસનીય પંડિતો દ્વારા કરવામાં આવે છે.",
    heroSubText2:
      "📿 શુદ્ધતા અને ભક્તિ સાથે તમારા ઘરમાં શાંતિ, સમૃદ્ધિ અને સકારાત્મક ઊર્જા લાવવાનો અમારો સંકલ્પ.",
    bookPoojaNow: "🕉️ હમણાં જ તમારી પૂજા બુક કરો",
    bookAstrology: "🔮 જ્યોતિષ સત્ર બુક કરો",
    servicesTitle: "અમારી દિવ્ય સેવાઓ",
    poojaServices: "પૂજા સેવાઓ",
    astrologyServices: "જ્યોતિષ",
    onlinePooja: "ઓનલાઈન / ઈ-પૂજા",
    learnMore: "વધુ જાણો →",
    aboutTitle: "પંડિત આદિત્ય નારાયણજીને મળો",
    aboutText:
      "ભારતભરમાં 12 વર્ષથી વધુ સમયથી પવિત્ર વિધિઓ કરવાનો અનુભવ ધરાવતા, પંડિત આદિત્ય નારાયણજી સનાતન વિધિ મુજબ કરવામાં આવતી અધિકૃત વૈદિક પૂજાઓ માટે જાણીતા છે. તેમના પિતા, એક આદરણીય પૂજારીના માર્ગદર્શન હેઠળ, તેઓ ભક્તિ અને આધ્યાત્મિક સેવાનો વારસો ચાલુ રાખે છે.",
    readMore: "વધુ વાંચો",
    whyChooseUsTitle: "અમને કેમ પસંદ કરો?",
    spiritualGuides: "આધ્યાત્મિક માર્ગદર્શકો",
    guidesDesc: "પૂજારીઓ, પંડિતો, ધાર્મિક નિષ્ણાતો અને સલાહકારો",
    typesOfPooja: "પૂજાના પ્રકારો",
    poojaDesc: "બધા મુખ્ય વૈદિક વિધિઓ અને સમારોહને આવરી લે છે",
    poojasPerformed: "પૂજાઓ કરવામાં આવી",
    performedDesc: "સમગ્ર ભારતમાં શાંતિ અને આશીર્વાદ લાવે છે",
    popularPoojasTitle: "સૌથી વધુ લોકપ્રિય પૂજાઓ",
    bookNow: "હમણાં બુક કરો",
    testimonialsTitle: "ભક્તિના શબ્દો",
    bookingTitle: "એક દિવ્ય અનુભવ બુક કરો",
    fullName: "પૂરું નામ",
    phone: "ફોન નંબર",
    poojaType: "પૂજાનો પ્રકાર",
    preferredDate: "પસંદગીની તારીખ",
    message: "વધારાનો સંદેશ",
    sendOnWhatsApp: "WhatsApp પર બુકિંગ વિનંતી મોકલો",
    footerContact: "વૈદિક પૂજા અને જ્યોતિષ સેવાઓ",
    footerSpecialPoojas: "વિશેષ પૂજા સેવાઓ",
    footerPoojaServices: "પૂજા સેવાઓ",
    footerQuickLinks: "ઝડપી લિંક્સ",
    footerContactInfo: "સંપર્ક માહિતી",
    // Astrology page translations
    astrologyHeroTitle: "જ્યોતિષની શક્તિની શોધ કરો — વિશેષજ્ઞ માર્ગદર્શન સાથે",
    all: "બધા",
    marriage: "લગ્ન",
    career: "કારકિર્દી",
    health: "સ્વાસ્થ્ય",
    finance: "નાણાકીય",
    spiritual: "આધ્યાત્મિક",
    footerCTA: "હમણાં જ વ્હાટ્સએપ પર તમારી જ્યોતિષ સલાહ શેડ્યૂલ કરો 📱।",
    consultationPrice: "સલાહ શરૂ થાય છે",
    bookYourSession: "તમારું સત્ર બુક કરો!",
    consultNow: "હમણાં સલાહ લો",
  },
};

interface LanguageContextType {
  language: string;
  setLanguage: React.Dispatch<React.SetStateAction<string>>;
  t: any;
}

const LanguageContext = createContext<LanguageContextType>({
  language: "en",
  setLanguage: () => { },
  t: translations.en,
});

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguage] = useState("en");
  const t = translations[language] || translations.en;
  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useTranslation = () => useContext(LanguageContext);
